"""Setup database

Revision ID: 0d2bb1afb90a
Revises:
Create Date: 2025-12-05 13:48:03.347169

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d2bb1afb90a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_event",
        sa.Column("raw_event_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "PROCESSING", "DONE", "FAILED", name="event_status"), nullable=False),
        sa.PrimaryKeyConstraint("raw_event_id"),
    )
    op.create_index("ix_raw_events_user_time", "raw_event", ["user_id", "timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_events_user_time", table_name="raw_event")
    op.drop_table("raw_event")
    # ### end Alembic commands ###
