"""Add enriched_event table

Revision ID: 33cbcc90f0fc
Revises: 0d2bb1afb90a
Create Date: 2025-12-05 14:41:16.245063

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33cbcc90f0fc"
down_revision: Union[str, Sequence[str], None] = "0d2bb1afb90a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enriched_event",
        sa.Column("enriched_event_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("raw_event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("semantic_label", sa.String(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=True),
        sa.Column("page_path", sa.String(), nullable=True),
        sa.Column("page_title", sa.String(), nullable=True),
        sa.Column("element_type", sa.String(), nullable=True),
        sa.Column("element_text", sa.String(), nullable=True),
        sa.Column("element_selector", sa.String(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raw_event_id"],
            ["raw_event.raw_event_id"],
        ),
        sa.PrimaryKeyConstraint("enriched_event_id"),
    )
    op.create_index("ix_enriched_session_timestamp", "enriched_event", ["session_id", "timestamp"], unique=False)
    op.create_index("ix_enriched_timestamp", "enriched_event", ["timestamp"], unique=False)
    op.create_index("ix_enriched_user_timestamp", "enriched_event", ["user_id", "timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_enriched_user_timestamp", table_name="enriched_event")
    op.drop_index("ix_enriched_timestamp", table_name="enriched_event")
    op.drop_index("ix_enriched_session_timestamp", table_name="enriched_event")
    op.drop_table("enriched_event")
    # ### end Alembic commands ###
