"""Add updated_at to raw_events

Revision ID: 35f1eb8d380e
Revises: 913ba7ffd15a
Create Date: 2025-12-06 12:15:37.786966

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35f1eb8d380e"
down_revision: Union[str, Sequence[str], None] = "913ba7ffd15a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("page_views_count", sa.Integer(), nullable=False),
        sa.Column("clicks_count", sa.Integer(), nullable=False),
        sa.Column("first_page", sa.String(), nullable=True),
        sa.Column("last_page", sa.String(), nullable=True),
        sa.Column("session_summary", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index("ix_session_active_activity", "session", ["is_active", "last_activity_at"], unique=False)
    op.create_index("ix_session_user_active", "session", ["user_id", "is_active"], unique=False)
    op.create_index("ix_session_user_started", "session", ["user_id", "started_at"], unique=False)
    op.add_column(
        "raw_event",
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_event", "updated_at")
    op.drop_index("ix_session_user_started", table_name="session")
    op.drop_index("ix_session_user_active", table_name="session")
    op.drop_index("ix_session_active_activity", table_name="session")
    op.drop_table("session")
    # ### end Alembic commands ###
