"""Add elements_chain to raw_event

Revision ID: 913ba7ffd15a
Revises: 33cbcc90f0fc
Create Date: 2025-12-05 14:57:27.409171

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "913ba7ffd15a"
down_revision: Union[str, Sequence[str], None] = "33cbcc90f0fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raw_event", sa.Column("elements_chain", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_event", "elements_chain")
    # ### end Alembic commands ###
