"""Remove 'PROCESSING' from status enum

Revision ID: c758e4339c68
Revises: 35f1eb8d380e
Create Date: 2025-12-06 12:33:46.546726

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c758e4339c68"
down_revision: Union[str, Sequence[str], None] = "35f1eb8d380e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_event", "status")
    op.add_column(
        "raw_event",
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "DONE", "FAILED", name="event_status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_event", "status")
    op.add_column(
        "raw_event",
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "PROCESSING", "DONE", "FAILED", name="event_status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
