from datetime import timedelta

from app.models import ActionType, Severity
from app.services.pattern_detection import EventFilter, PatternRule, SessionFilter

PATTERN_RULES: list[PatternRule] = [
    PatternRule(
        code="checkout_button_rage_click",
        description="User rage-clicked checkout button indicating payment/UX issues",
        severity=Severity.high,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="checkout",
        ),
        min_count=1,
    ),
    PatternRule(
        code="cart_abandonment_with_items",
        description="User added items to cart but didn't proceed to checkout within 15 minutes",
        severity=Severity.high,
        filter=EventFilter(semantic_contains="add to cart"),
        min_count=1,
        negative_filter=EventFilter(semantic_contains="checkout"),
        negative_time_window=timedelta(minutes=15),
    ),
    PatternRule(
        code="checkout_abandonment",
        description="User clicked checkout but didn't complete purchase",
        severity=Severity.high,
        filter=EventFilter(semantic_contains="checkout"),
        min_count=1,
        negative_filter=EventFilter(semantic_contains="item added to cart"),
        negative_time_window=timedelta(minutes=20),
    ),
    PatternRule(
        code="price_rage_click",
        description="User rage-clicked on price element suggesting confusion or frustration",
        severity=Severity.high,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="$",
        ),
        min_count=1,
    ),
    PatternRule(
        code="cart_quantity_struggle",
        description="User repeatedly rage-clicked quantity controls indicating UX issues",
        severity=Severity.high,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="+",
        ),
        min_count=2,
    ),
    PatternRule(
        code="product_image_rage_click",
        description="User rage-clicked product images suggesting slow loading or broken links",
        severity=Severity.medium,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="img",
        ),
        min_count=1,
    ),
    PatternRule(
        code="filter_rage_click",
        description="User rage-clicked filters or category buttons indicating poor filter UX",
        severity=Severity.medium,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="racing",  # category name
        ),
        min_count=2,
    ),
    PatternRule(
        code="cart_view_without_purchase",
        description="User viewed cart multiple times but never checked out",
        severity=Severity.medium,
        filter=EventFilter(semantic_contains="view cart"),
        min_count=3,
        negative_filter=EventFilter(semantic_contains="checkout"),
    ),
    PatternRule(
        code="excessive_cart_updates",
        description="User updated cart quantity many times suggesting indecision or UX issues",
        severity=Severity.medium,
        filter=EventFilter(semantic_contains="update cart quantity"),
        min_count=5,
        time_window=timedelta(minutes=10),
    ),
    PatternRule(
        code="product_comparison_paralysis",
        description="User viewed many products but didn't add any to cart",
        severity=Severity.medium,
        filter=EventFilter(semantic_contains="clicked"),
        min_count=8,
        negative_filter=EventFilter(semantic_contains="add to cart"),
        session_filter=SessionFilter(min_duration_seconds=120),
    ),
    PatternRule(
        code="navigation_confusion",
        description="User rage-clicked navigation elements suggesting confusing menu structure",
        severity=Severity.medium,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="navigation",
        ),
        min_count=1,
    ),
    PatternRule(
        code="continue_shopping_loop",
        description="User repeatedly clicked 'Continue Shopping' instead of checkout",
        severity=Severity.medium,
        filter=EventFilter(semantic_contains="continue shopping"),
        min_count=3,
        negative_filter=EventFilter(semantic_contains="checkout"),
    ),
    PatternRule(
        code="power_shopper",
        description="High engagement session with multiple product interactions",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="product"),
        min_count=10,
        session_filter=SessionFilter(min_duration_seconds=300),
    ),
    PatternRule(
        code="category_explorer",
        description="User actively explored different drone categories",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="button"),
        min_count=5,
        session_filter=SessionFilter(min_page_views=3),
    ),
    PatternRule(
        code="price_focused_browser",
        description="User repeatedly clicked on prices suggesting price comparison",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="$"),
        min_count=4,
        time_window=timedelta(minutes=10),
    ),
    PatternRule(
        code="favorite_toggler",
        description="User actively using favorite/wishlist feature",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="toggle favorite"),
        min_count=2,
    ),
    PatternRule(
        code="filter_power_user",
        description="User extensively using product filters for precise shopping",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="filter"),
        min_count=5,
        time_window=timedelta(minutes=10),
    ),
    PatternRule(
        code="demo_watcher",
        description="User engaged with product demo/video content",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="watch demo"),
        min_count=1,
    ),
    PatternRule(
        code="specific_product_focus",
        description="User repeatedly interacted with specific product suggesting high intent",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="phantom x pro"),  # specific product
        min_count=3,
    ),
    PatternRule(
        code="cart_item_remover",
        description="User removed items from cart multiple times suggesting price sensitivity or comparison",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="remove from cart"),
        min_count=2,
    ),
    PatternRule(
        code="form_rage_click",
        description="User rage-clicked form suggesting validation errors or confusion",
        severity=Severity.high,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="form",
        ),
        min_count=1,
    ),
    PatternRule(
        code="svg_rage_click_pattern",
        description="User rage-clicked SVG icons suggesting non-interactive elements appearing clickable",
        severity=Severity.medium,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="svg",
        ),
        min_count=2,
    ),
    PatternRule(
        code="shop_now_frustration",
        description="User rage-clicked 'Shop Now' button suggesting broken CTA or slow page load",
        severity=Severity.high,
        filter=EventFilter(
            action_type=ActionType.rage_click,
            semantic_contains="shop now",
        ),
        min_count=1,
    ),
    PatternRule(
        code="racing_category_interest",
        description="Strong interest in racing drone category",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="racing"),
        min_count=4,
        session_filter=SessionFilter(min_duration_seconds=60),
    ),
    PatternRule(
        code="professional_vs_consumer_comparison",
        description="User comparing professional vs consumer drone categories",
        severity=Severity.low,
        filter=EventFilter(semantic_contains="professional"),
        min_count=2,
        session_filter=SessionFilter(min_page_views=2),
    ),
]
